In [12]:
import pandas as pd

csv_file = '/Users/maxjiang/Desktop/WBData.csv'
df = pd.read_csv(csv_file)

create_table = "CREATE TABLE wb_data (\n"
for col in df.columns:
    col_name = col.replace(" ", "_").replace("[", "").replace("]", "").replace(".", "_")
    dtype = "REAL" if pd.api.types.is_numeric_dtype(df[col]) else "TEXT"
    create_table += f"    {col_name} {dtype},\n"
create_table = create_table.rstrip(",\n") + "\n);"

insert_statements = []
for _, row in df.iterrows():
    values = ", ".join([f"'{x}'" if pd.notna(x) else "NULL" for x in row])
    insert_statements.append(f"INSERT INTO wb_data VALUES ({values});")

sql_script = create_table + "\n\n" + "\n".join(insert_statements)

with open("wb_data.sql", "w") as f:
    f.write(sql_script)

print("SQL script saved to wb_data.sql")

SQL script saved to wb_data.sql

In [1]:
import dask.datasets

In [2]:
import dask.dataframe as dd
from dask_sql import Context

c = Context()
df = dd.read_csv("/Users/maxjiang/Desktop/WBData.csv")

c.create_table("wb_data", df)

In [3]:
query = "SELECT * FROM wb_data"
result = c.sql(query)

In [9]:
print(df.columns)

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1974 [YR1974]', '1975 [YR1975]', '1976 [YR1976]', '1977 [YR1977]',
       '1978 [YR1978]', '1979 [YR1979]', '1980 [YR1980]', '1981 [YR1981]',
       '1982 [YR1982]', '1983 [YR1983]', '1984 [YR1984]', '1985 [YR1985]',
       '1986 [YR1986]', '1987 [YR1987]', '1988 [YR1988]', '1989 [YR1989]',
       '1990 [YR1990]', '1991 [YR1991]', '1992 [YR1992]', '1993 [YR1993]',
       '1994 [YR1994]', '1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]',
       '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]',
       '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]',
       '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]',
       '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]',
       '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]',
       '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]',
       '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [16]:
import dask.dataframe as dd
from dask_sql import Context

c = Context()
df = dd.read_csv("/Users/maxjiang/Desktop/WBData.csv")
c.create_table("wb_data", df)

selected_columns = [
    "Country Name", "Series Name",
    "1975 [YR1975]", "1976 [YR1976]", "2020 [YR2020]", "2021 [YR2021]", "2022 [YR2022]", "2023 [YR2023]"
]
filtered_df = df[selected_columns]

filtered_df = filtered_df.rename(
    columns={
        "1974 [YR1974]": "Year1974",
        "1975 [YR1975]": "Year1975",
        "1976 [YR1976]": "Year1976",
        "1977 [YR1977]": "Year1977",
        "1978 [YR1978]": "Year1978",
        "1979 [YR1979]": "Year1979",
        "1980 [YR1980]": "Year1980",
        "1981 [YR1981]": "Year1981",
        "1982 [YR1982]": "Year1982",
        "1983 [YR1983]": "Year1983",
        "1984 [YR1984]": "Year1984",
        "1985 [YR1985]": "Year1985",
        "1986 [YR1986]": "Year1986",
        "1987 [YR1987]": "Year1987",
        "1988 [YR1988]": "Year1988",
        "1989 [YR1989]": "Year1989",
        "1990 [YR1990]": "Year1990",
        "1991 [YR1991]": "Year1991",
        "1992 [YR1992]": "Year1992",
        "1993 [YR1993]": "Year1993",
        "1994 [YR1994]": "Year1994",
        "1995 [YR1995]": "Year1995",
        "1996 [YR1996]": "Year1996",
        "1997 [YR1997]": "Year1997",
        "1998 [YR1998]": "Year1998",
        "1999 [YR1999]": "Year1999",
        "2000 [YR2000]": "Year2000",
        "2001 [YR2001]": "Year2001",
        "2002 [YR2002]": "Year2002",
        "2003 [YR2003]": "Year2003",
        "2004 [YR2004]": "Year2004",
        "2005 [YR2005]": "Year2005",
        "2006 [YR2006]": "Year2006",
        "2007 [YR2007]": "Year2007",
        "2008 [YR2008]": "Year2008",
        "2009 [YR2009]": "Year2009",
        "2010 [YR2010]": "Year2010",
        "2011 [YR2011]": "Year2011",
        "2012 [YR2012]": "Year2012",
        "2013 [YR2013]": "Year2013",
        "2014 [YR2014]": "Year2014",
        "2015 [YR2015]": "Year2015",
        "2016 [YR2016]": "Year2016",
        "2017 [YR2017]": "Year2017",
        "2018 [YR2018]": "Year2018",
        "2019 [YR2019]": "Year2019",
        "2020 [YR2020]": "Year2020",
        "2021 [YR2021]": "Year2021",
        "2022 [YR2022]": "Year2022",
        "2023 [YR2023]": "Year2023",

    }
)


filtered_df = filtered_df.replace("..", None)

year_columns = [
    "Year1974", "Year1975", 
    "Year1976", "Year1977", "Year1978", "Year1979", "Year1980", "Year1981", 
    "Year1982", "Year1983", "Year1984", "Year1985", "Year1986", "Year1987", 
    "Year1988", "Year1989", "Year1990", "Year1991", "Year1992", "Year1993", 
    "Year1994", "Year1995", "Year1996", "Year1997", "Year1998", "Year1999", 
    "Year2000", "Year2001", "Year2002", "Year2003", "Year2004", "Year2005", 
    "Year2006", "Year2007", "Year2008", "Year2009", "Year2010", "Year2011", 
    "Year2012", "Year2013", "Year2014", "Year2015", "Year2016", "Year2017", 
    "Year2018", "Year2019", "Year2020", "Year2021", "Year2022", "Year2023"
]

numeric_cols = year_columns

for i, col in enumerate(year_columns):
    if i >= 2:  
        prev1, prev2 = year_columns[i - 1], year_columns[i - 2]
        query = f"""
            UPDATE wb_data_cleaned
            SET `{col}` = COALESCE(`{col}`, (`{prev1}` + `{prev2}`) / 2)
            WHERE `{col}` IS NULL;
        """
        c.sql(query)

for col in year_columns:
    query = f"""
        UPDATE wb_data_cleaned
        SET `{col}` = COALESCE(`{col}`, 
            (SELECT AVG(`{col}`) FROM wb_data_cleaned WHERE `{col}` IS NOT NULL))
        WHERE `{col}` IS NULL;
    """
    c.sql(query)

categorical_columns = ["Country Name", "Series Name"]
for col in categorical_columns:
    query = f"""
        UPDATE wb_data_cleaned
        SET `{col}` = COALESCE(`{col}`, 
            (SELECT `{col}` FROM wb_data_cleaned 
             GROUP BY `{col}` ORDER BY COUNT(*) DESC LIMIT 1))
        WHERE `{col}` IS NULL;
    """
    c.sql(query)

for col in numeric_cols:
    filtered_df[col] = filtered_df[col].map_partitions(pd.to_numeric, errors='coerce')

def fill_missing_values(df):
    df["Year2022"] = df["Year2022"].fillna((df["Year2020"] + df["Year2021"]) / 2)
    df["Year2023"] = df["Year2023"].fillna((df["Year2021"] + df["Year2022"]) / 2)
    return df

filled_df = filtered_df.map_partitions(fill_missing_values)
c.create_table("wb_data_Further_cleaned", filled_df)

filled_df.compute().to_csv("/Users/maxjiang/Desktop/WBData_Further_Cleaned.csv", index=False)

In [ ]:
#Improved Version
import dask.dataframe as dd
from dask_sql import Context
import pandas as pd

c = Context()
df = dd.read_csv("/Users/maxjiang/Desktop/WBData.csv")
c.create_table("wb_data", df)

year_columns = [f"Year{year}" for year in range(1970, 2020)]
rename_mapping = {f"{year} [YR{year}]": f"Year{year}" for year in range(1970, 2020)}
rename_mapping.update({"Country Name": "CountryName", "Series Name": "SeriesName"})
filtered_df = df.rename(columns=rename_mapping)

filtered_df = filtered_df.replace("..", None)

numeric_cols = year_columns
for col in numeric_cols:
    filtered_df[col] = filtered_df[col].map_partitions(pd.to_numeric, errors='coerce')

def fill_missing_values(df):
    for i, col in enumerate(year_columns):
        if i >= 2:
            prev1, prev2 = year_columns[i - 1], year_columns[i - 2]
            df[col] = df[col].fillna((df[prev1] + df[prev2]) / 2)
    return df

filled_df = filtered_df.map_partitions(fill_missing_values)

for col in numeric_cols:
    query = f"""
        UPDATE wb_data_cleaned
        SET `{col}` = COALESCE(`{col}`, 
            (SELECT AVG(`{col}`) FROM wb_data_cleaned WHERE `{col}` IS NOT NULL))
        WHERE `{col}` IS NULL;
    """
    c.sql(query)

categorical_columns = ["CountryName", "SeriesName"]
for col in categorical_columns:
    query = f"""
        UPDATE wb_data_cleaned
        SET `{col}` = COALESCE(`{col}`, 
            (SELECT `{col}` FROM wb_data_cleaned 
             GROUP BY `{col}` ORDER BY COUNT(*) DESC LIMIT 1))
        WHERE `{col}` IS NULL;
    """
    c.sql(query)

filled_df.compute().to_csv("/Users/maxjiang/Desktop/WBData_Further_Cleaned.csv", index=False)

In [ ]:
#Final Check using Python
'''
correct_file_path = '/Users/maxjiang/Desktop/WBData.csv'
data = pd.read_csv(correct_file_path)

data.columns = [col.strip().replace(' [', '_').replace(']', '').replace('YR', 'Year') for col in data.columns]

data.replace("..", pd.NA, inplace=True)

for col in data.columns[5:]:  # Assuming first 5 columns are non-numeric metadata
    data[col] = pd.to_numeric(data[col], errors='coerce')

years = [col for col in data.columns if 'Year' in col]
recent_years_average = data[years[-2:]].mean(axis=1, skipna=True)
for col in years:
    data[col] = data[col].fillna(recent_years_average)

output_corrected_path = '/Users/maxjiang/Desktop/WBData_Cleaned.csv'
data.to_csv(output_corrected_path, index=False)

for row_index in [8, 9]:  # 9th and 10th rows (zero-based index)
    row_last_two = data.iloc[row_index][years[-2:]]
    if row_last_two.isnull().all():
        overall_average = data.iloc[row_index][years].mean(skipna=True)
        data.loc[row_index, years[-2:]] = overall_average

data.to_csv(output_corrected_path, index=False)

updated_rows = data.iloc[[8, 9]][years[-2:]]
updated_rows

row_index = 8  
row_last_two = data.iloc[row_index][years[-2:]]

if row_last_two.isnull().all():
    overall_average = data.iloc[row_index][years].mean(skipna=True)
    data.loc[row_index, years[-2:]] = overall_average

data.to_csv(output_corrected_path, index=False)

updated_ninth_row_last_two = data.iloc[row_index][years[-2:]]
updated_ninth_row_last_two

previous_two_years = years[-4:-2]

previous_two_years_average = data.loc[row_index, previous_two_years].mean(skipna=True)

data.loc[row_index, years[-2:]] = previous_two_years_average

data.to_csv(output_corrected_path, index=False)
corrected_ninth_row_last_two = data.loc[row_index, years[-2:]]
corrected_ninth_row_last_two

columns_to_remove = ['Series Code', 'Country Code']
data.drop(columns=columns_to_remove, inplace=True, errors='ignore')

data.columns = [col.split('_')[-1] if 'Year' in col else col for col in data.columns]

output_further_cleaned_path = '/Users/maxjiang/Desktop/WBData_Further_Cleaned.csv'
data.to_csv(output_further_cleaned_path, index=False)
'''